services:

  mysql:
    container_name: backend_db
    volumes:
      - my-db:/var/lib/mysql
      - ./init-db.sql:/init-db.sql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_db

    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"show databases;\""
      timeout: 20s
      retries: 10
    restart: on-failure
    command: --init-file /init-db.sql

  web:
    container_name: backend_app
    build:
      context: .
      args:
        SERVICE: server
    env_file:
      - ./docker/docker-compose.env
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: [ "/usr/local/bin/entrypoint" ]
    command: [ "rails", "server", "-b", "0.0.0.0" ]
    depends_on:
      mysql:
        condition: "service_healthy"
        
volumes:
  my-db:
