# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  checkout_timeout: 5
  connect_timeout: 30
  read_timeout: 60
  reconnect: true
  host: <%= ENV['RDS_HOSTNAME'] || 'localhost' %>
  username: <%= ENV['RDS_USERNAME'] || 'root' %>
  password: <%= ENV['RDS_PASSWORD'] || 'root' %>
  port: <%= ENV['RDS_PORT']  || 3306%>

development:
  <<: *default
  pool: 25
  database: <%= ENV['RDS_DB_NAME'] || 'backend_db' %>

test:
  <<: *default
  reconnect: false
  pool: 8
  database: <%= 'test_backend_db' %>
